In [11]:
#1. Create an empty and a full array of size 3x3.
import numpy as np

# Create an empty array of size 3x3
empty_array = np.empty((3, 3))

# Create a full array of size 3x3 with a specific value (let's say 5)
full_array = np.full((3, 3), 5)

print("Empty Array:")
print(empty_array)

print("\nFull Array:")
print(full_array)


Empty Array:
[[4.9e-324 9.9e-324 1.5e-323]
 [1.5e-323 2.5e-323 3.0e-323]
 [3.5e-323 3.5e-323 4.9e-323]]

Full Array:
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [12]:
# 2. Generate an array of 25 random numbers sampled from a standard normal
# distribution.
import numpy as np

# Generate an array of 25 random numbers sampled from a standard normal distribution
random_array = np.random.randn(25)

print("Random Array:")
print(random_array)


Random Array:
[-1.15144837 -1.04578507  1.22810488  0.77729475 -0.17855145 -0.22496744
 -0.47014478 -1.10272594  1.22438476 -0.36409587  0.58717    -0.79152903
  0.19705521 -1.08291834  0.86359958  0.70476542 -0.33274607  0.81149727
  0.70590309 -0.13955614 -0.14202616  0.81934923 -2.01005831  1.17116749
 -1.02842179]


In [13]:
#3. Find Dot product of two arrays.
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Find the dot product
dot_product = np.dot(array1, array2)

print("Dot Product:", dot_product)


Dot Product: 32


In [14]:
#4. Sort the below array along the row, along the column and as a whole.
# [3, 7, 1]
# [10, 3, 2]
# [5, 6, 7]

import numpy as np

# Create the array
array = np.array([[3, 7, 1],
                  [10, 3, 2],
                  [5, 6, 7]])

# Sort along the row (axis=1)
sorted_row = np.sort(array, axis=1)

# Sort along the column (axis=0)
sorted_column = np.sort(array, axis=0)

# Sort the array as a whole
sorted_whole = np.sort(array, axis=None)

print("Sorted along the row:")
print(sorted_row)

print("\nSorted along the column:")
print(sorted_column)

print("\nSorted as a whole:")
print(sorted_whole)


Sorted along the row:
[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]

Sorted along the column:
[[ 3  3  1]
 [ 5  6  2]
 [10  7  7]]

Sorted as a whole:
[ 1  2  3  3  5  6  7  7 10]


In [15]:
# 5. Make a list of 3 numpy arrays and find the mean of all the numpy arrays and output
# them as a list.
import numpy as np

# Create a list of 3 NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

array_list = [array1, array2, array3]

# Calculate the mean of each array
mean_list = [np.mean(arr) for arr in array_list]

print("List of Arrays:")
for i, arr in enumerate(array_list, start=1):
    print(f"Array {i}:", arr)

print("\nMean of Each Array:")
for i, mean in enumerate(mean_list, start=1):
    print(f"Array {i} Mean:", mean)


List of Arrays:
Array 1: [1 2 3]
Array 2: [4 5 6]
Array 3: [7 8 9]

Mean of Each Array:
Array 1 Mean: 2.0
Array 2 Mean: 5.0
Array 3 Mean: 8.0


In [16]:
# 6. Make a numpy array containing the string 'PHP C# Python C Java C++' as the only
# element, then split it on the basis of spaces
import numpy as np

# Create a numpy array with a single string element
string_array = np.array(['PHP C# Python C Java C++'])

# Split the string on spaces
split_result = np.char.split(string_array)

# Access the split result as a list
split_list = split_result[0]

print("Original String Array:")
print(string_array)

print("\nSplit Result as a List:")
print(split_list)


Original String Array:
['PHP C# Python C Java C++']

Split Result as a List:
['PHP', 'C#', 'Python', 'C', 'Java', 'C++']
